blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('posts.urls')),
    path("", include('gallery.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gallery/urls.py
from django.urls import path
from . import views

app_name = "gallery"

urlpatterns = [
    path("gallery/", views.GalleryList.as_view(), name="list"),
    path("gallery/<int:pk>", views.GalleryDetail.as_view(), name="gallery_detail"),
    path("gallery/<int:pk>/images/<int:picture_pk>", views.PictureDetail.as_view(), name="picture_detail")
]

posts/urls.py
from django.urls import path
from django.views.generic.base import TemplateView

from . import views

app_name = "posts"

urlpatterns = [
    # path("", views.home_page, name="home"),
    # path("", TemplateView.as_view(template_name="posts/home.html")),
    path("", views.HomePageView.as_view(), name="home"),
    # path("posts/", views.list_posts, name="list"),
    path("posts/", views.PostList.as_view(), name="list"),
    # path("posts/<int:id>/", views.post_details, name="details"),
    path("posts/<int:pk>/", views.PostDetails.as_view(), name="details"),
    # path("posts/add/", views.add_post, name="add"),
    # path("posts/add/", views.create_post, name="add"),
    path("posts/add/", views.PostAdd.as_view(), name="add"),

    path("categories/", views.CategoriesList.as_view(), name="categories"),
    path("categories/add", views.CategoryCreate.as_view(), name="create-category"),
    path("myview/", views.my_view, name="translation_example")
]

gallery/models.py
from django.db import models
from posts.models import TimestampedModel


class Gallery(TimestampedModel):
    title = models.CharField(max_length=200)

    def __str__(self):
        return self.title


class Picture(TimestampedModel):
    img = models.ImageField(upload_to="gallery/%Y/%m/%d")
    text = models.CharField(max_length=200)
    gallery = models.ForeignKey(Gallery, on_delete=models.CASCADE)

    def __str__(self):
        return self.text

posts/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse_lazy, reverse


class TimestampedModel(models.Model):
    modified_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        abstract = True


class Category(TimestampedModel):
    name = models.CharField(max_length=200)
    description = models.TextField()

    def __str__(self):
        return self.name

    @staticmethod
    def get_absolute_url():
        return reverse_lazy("posts:categories")


class Post(TimestampedModel):
    title = models.CharField(max_length=200)
    content = models.TextField()
    user = models.ForeignKey(User, related_name="posts", on_delete=models.CASCADE)
    published = models.BooleanField(default=False)
    likes = models.IntegerField(default=0)
    category = models.ForeignKey(Category, related_name="posts", on_delete=models.CASCADE, default=1)
    standout_image = models.ImageField(upload_to="posts/", blank=True, null=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("posts:details", kwargs={"pk": self.pk})

posts/forms.py
from django import forms
from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ["title", "content"]

gallery/views.py
from django.shortcuts import render
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from .models import Gallery, Picture


class GalleryList(ListView):
    model = Gallery
    paginate_by = 10


class GalleryDetail(DetailView):
    model = Gallery


class PictureDetail(DetailView):
    model = Picture

    def get_queryset(self):
        picture_pk = self.kwargs['picture_pk']
        object = Picture.objects.filter(pk=picture_pk)
        return object

posts/views.py
from django.core.paginator import Paginator
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from django.views.generic.edit import CreateView
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.views.generic.base import TemplateView
from django.utils.translation import gettext as _

from posts.models import Post, Category
from .forms import PostForm


def home_page(request):
    return render(
        request,
        "posts/home.html",
        {}
    )


class HomePageView(TemplateView):
    template_name = "posts/home.html"


def list_posts(request):
    posts = Post.objects.all()
    paginator = Paginator(posts, 3)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    return render(
        request,
        "posts/post_list.html",
        {"posts": page_obj}
    )


class PostList(ListView):
    model = Post
    template_name = "posts/list.html"
    context_object_name = "posts"
    paginate_by = 3


def post_details(request, pk: int):
    post = get_object_or_404(Post, pk=pk)
    return render(
        request,
        "posts/post_detail.html",
        {"object": post}
    )


class PostDetails(DetailView):
    model = Post


def add_post(request):
    if request.method == 'POST':
        title = request.POST.get("title"),
        content = request.POST.get("content")
        Post.objects.create(
            title=title,
            content=content,
            user=request.user,
        )
        return redirect("posts:list")
    return render(
        request,
        "posts/post_form.html",
        {}
    )


def create_post(request):
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            post.save()
    form = PostForm()
    return render(
        request,
        "posts/post_form.html",
        {"form": form}
    )


class PostAdd(CreateView):
    model = Post
    fields = ["title", "content"]

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class CategoriesList(ListView):
    model = Category
    paginate_by = 10


class CategoryCreate(CreateView):
    model = Category
    fields = ["name", "description"]


def my_view(request):
    output = _("Welcome to my site.")
    return HttpResponse(output)

gallery/templates/gallery/gallery_detail.html
{% extends "posts/home.html" %}
{% load custom_tags %}
{% load custom_filters %}
{% load thumbnail %}

{% block content %}
    <h1>{{ object.title|scream }}</h1>

    {%  for image in object.picture_set.all %}
    <p>
    {% thumbnail image.img "250" crop="center" as im %}
        <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}">
    {% endthumbnail %}
    </p>
    {%  endfor %}

{% endblock %}

gallery/templates/gallery/gallery_list.html
{% extends "posts/home.html" %}

{% block content %}
<h1>Lista postów</h1>


    {% if page_obj %}
    {% for item in page_obj %}
        <div class="card mb-1">
        <a href="{% url 'gallery:gallery_detail' item.id%}">
            <div class="card-body">
              <p class="card-title">{{ item.title }}</p>
            </div>
            </a>
        </div>
    {% endfor %}

    {% if page_obj.has_other_pages %}
    <div class="btn-group" role="group" aria-label="Item pagination">
        {% if page_obj.has_previous %}
            <a href="?page={{ page_obj.previous_page_number }}" class="btn btn-outline-primary">&laquo;</a>
        {% endif %}

        {% for page_number in page_obj.paginator.page_range %}
            {% if page_obj.number == page_number %}
                <button class="btn btn-outline-primary active">
                    <span>{{ page_number }} <span class="sr-only">(current)</span></span>
                </button>
            {% else %}
                <a href="?page={{ page_number }}" class="btn btn-outline-primary">
                    {{ page_number }}
                </a>
            {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}" class="btn btn-outline-primary">&raquo;</a>
        {% endif %}
    </div>
    {% endif %}
{% else %}
    <p>No items found.</p>
{% endif %}

{% endblock %}

gallery/templates/gallery/picture_detail.html
{% extends "posts/home.html" %}
{% load custom_tags %}
{% load custom_filters %}
{% load thumbnail %}

{% block content %}
    <h1>{{ object.gallery.title|scream }}</h1>
    <img src="{{ object.img.url }}" alt="{{ object.text }}">


{% endblock %}

posts/templates/posts/category_form.html
{% extends "posts/home.html" %}
{%  load crispy_forms_tags %}

{% block content %}
    <h1>Dodaj kategorię</h1>
    <form method="post">
    {%  csrf_token %}
{#    <p>#}
{#        <label for="p_title">Title</label>#}
{#        <input type="text" id="p_title" name="title">#}
{#    </p>#}
{#        <textarea id="p_content" name="content" rows="4" cols="50">Content</textarea>#}
        {{ form|crispy }}

    <input type="submit" class="btn btn-success" value="Create">
    </form>



{% endblock %}

posts/templates/posts/category_list.html
{% extends "posts/home.html" %}

{% block content %}
<h1>Lista kategorii</h1>


    {% if page_obj %}
    {% for item in page_obj %}
        <div class="card mb-1">
        <a href="{% url 'posts:details' item.id%}">
            <div class="card-body">
              <p class="card-title">{{ item }}</p>
            </div>
            </a>
        </div>
    {% endfor %}

    {% if page_obj.has_other_pages %}
    <div class="btn-group" role="group" aria-label="Item pagination">
        {% if page_obj.has_previous %}
            <a href="?page={{ page_obj.previous_page_number }}" class="btn btn-outline-primary">&laquo;</a>
        {% endif %}

        {% for page_number in page_obj.paginator.page_range %}
            {% if page_obj.number == page_number %}
                <button class="btn btn-outline-primary active">
                    <span>{{ page_number }} <span class="sr-only">(current)</span></span>
                </button>
            {% else %}
                <a href="?page={{ page_number }}" class="btn btn-outline-primary">
                    {{ page_number }}
                </a>
            {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}" class="btn btn-outline-primary">&raquo;</a>
        {% endif %}
    </div>
    {% endif %}
{% else %}
    <p>No items found.</p>
{% endif %}

{% endblock %}

posts/templates/posts/home.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="styles.css">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="#">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Link</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Dropdown
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <li><a class="dropdown-item" href="#">Action</a></li>
                <li><a class="dropdown-item" href="#">Another action</a></li>
                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item" href="#">Something else here</a></li>
              </ul>
            </li>
            <li class="nav-item">
              <a class="nav-link disabled">Disabled</a>
            </li>
          </ul>
          <form class="d-flex" role="search">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Search</button>
          </form>
        </div>
      </div>
    </nav>
    <div class="container my-5">
      {% block content %}
      <h1>Hello, world!</h1>
      <div class="col-lg-8 px-0">
        <p class="fs-5">You've successfully loaded up the Bootstrap starter example. It includes <a href="https://getbootstrap.com/">Bootstrap 5</a> via the <a href="https://www.jsdelivr.com/package/npm/bootstrap">jsDelivr CDN</a> and includes an additional CSS and JS file for your own code.</p>
        <p>Feel free to download or copy-and-paste any parts of this example.</p>

        <hr class="col-1 my-4">

        <a href="https://getbootstrap.com" class="btn btn-primary">Read the Bootstrap docs</a>
        <a href="https://github.com/twbs/examples" class="btn btn-secondary">View on GitHub</a>
      </div>
      {% endblock %}
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <script src="main.js"></script>
  </body>
</html>

posts/templates/posts/post_detail.html
{% extends "posts/home.html" %}

{% block content %}
    <h1>{{ object.title }}</h1>
{% endblock %}

posts/templates/posts/post_form.html
{% extends "posts/home.html" %}
{%  load crispy_forms_tags %}

{% block content %}
    <h1>Dodaj post</h1>
    <form method="post">
    {%  csrf_token %}
{#    <p>#}
{#        <label for="p_title">Title</label>#}
{#        <input type="text" id="p_title" name="title">#}
{#    </p>#}
{#        <textarea id="p_content" name="content" rows="4" cols="50">Content</textarea>#}
        {{ form|crispy }}

    <input type="submit" class="btn btn-success" value="Create">
    </form>



{% endblock %}

posts/templates/posts/post_list.html
{% extends "posts/home.html" %}

{% block content %}
<h1>Lista postów</h1>


    {% if page_obj %}
    {% for item in page_obj %}
        <div class="card mb-1">
        <a href="{% url 'posts:details' item.id%}">
            <div class="card-body">
              <p class="card-title">{{ item.title }}</p>
            </div>
            </a>
        </div>
    {% endfor %}

    {% if page_obj.has_other_pages %}
    <div class="btn-group" role="group" aria-label="Item pagination">
        {% if page_obj.has_previous %}
            <a href="?page={{ page_obj.previous_page_number }}" class="btn btn-outline-primary">&laquo;</a>
        {% endif %}

        {% for page_number in page_obj.paginator.page_range %}
            {% if page_obj.number == page_number %}
                <button class="btn btn-outline-primary active">
                    <span>{{ page_number }} <span class="sr-only">(current)</span></span>
                </button>
            {% else %}
                <a href="?page={{ page_number }}" class="btn btn-outline-primary">
                    {{ page_number }}
                </a>
            {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}" class="btn btn-outline-primary">&raquo;</a>
        {% endif %}
    </div>
    {% endif %}
{% else %}
    <p>No items found.</p>
{% endif %}

{% endblock %}